server:
  port: 9095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
    username: root
    password: 124578
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/web/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl 
mybatis:
  typeAliasesPackage: com.sgh.demo.domain
  mapperLocations: classpath:mapper/*.xml